# Circle tracking task with end-effector constraints


# MPC & sim parameters
ctrl_freq: 100         # Control frequency
RICCATI: False 


# OCP 
dt: 0.05                                             # OCP integration step 
N_h: 10                                              # Horizon length in nodes
maxiter: 9                                           # Max number of iterations 
solver_termination_tolerance: 0.0001              # Tolerance on KKT residual 
q0: [0., 1.0471975511965976, 0., -1.1344640137963142, 0.2,  0.7853981633974483, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                         # Initial robot joint velocity

T_REACH: 0.
T_CIRCLE: 2.

# CSSQP solver parameters
SOLVER: 'cssqp'
with_callbacks: False
use_filter_line_search: True
filter_size: 9
warm_start: True
max_qp_iter: 50    #125 
qp_termination_tol_abs: 0.00001
qp_termination_tol_rel: 0.00001
warm_start_y: False 
reset_rho: False


# Constraints terms
# to select from the list : 'stateBox', 'ctrlBox', 'translationBox', 'None'
WHICH_CONSTRAINTS: ['translationBox']



# 'translation'
eeLowerLimit: [-10.,-10, 0.]
eeUpperLimit: [10., 10, 10]
eeConstraintFrameName: 'contact'


# Cost function terms
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['translation', 'ctrlRegGrav', 'stateReg'] 

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [20., 20., 20., 10., 10., 10, 10., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]


 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegGravWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegGravWeight: 0.0001
ctrlRegGravWeightTerminal: 0.0001


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 5.
frameTranslationWeightTerminal: 10. 
frameTranslationRef: [0.4, -0., .25]
frameTranslationFrameName: 'contact'  

# armature
armature: [0., 0., 0., 0., 0., 0., 0.]
