# ROBOT : 'iiwa' 
# TASK  : end-effector position reaching task


# MPC & sim parameters
ctrl_freq: 1000         # Control frequency
RICCATI: False 


# General
SOLVER: 'sqp' # 'fddp'
dt: 0.05                                             # OCP integration step 
N_h: 10                                              # Horizon length in nodes
maxiter: 1                                           # Max number of iterations in DDP
solver_termination_tolerance: 0.0001                 # Tolerance on KKT residual 
q0: [0., 1.0471975511965976, 0., -1.1344640137963142, 0.2,  0.7853981633974483, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                         # Initial robot joint velocity



# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['translation', 'ctrlRegGrav', 'stateReg', 'stateLim'] 

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [10., 5, 5., 1., 1., 1., 1., 5., 5., 5., 5., 5., 5., 5.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.1
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]


 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegGravWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegGravWeight: 0.001
ctrlRegGravWeightTerminal: 0.001


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.]
frameTranslationWeight: 1.
frameTranslationWeightTerminal: 10. 
frameTranslationRef: [0.7, 0., 0.7]
frameTranslationFrameName: 'contact'  


 # 'velocity' : end-effector frame velocity (translation + rotation)
frameVelocityWeights:  [1., 1., 1., 0., 0., 0.]
frameVelocityWeight: 0.1
frameVelocityWeightTerminal: 10.
frameVelocityRef: [0., 0., 0., 0., 0., 0.]    
frameVelocityFrameName: 'contact'  


 # 'stateLim' : state limits
stateLimWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
stateLimWeight: 100.
stateLimWeightTerminal: 100.
coef_xlim: 0.9

 # 'ctrlLim' : torque limits
ctrlLimWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlLimWeight: 10.
coef_ulim: 1.

# armature
armature: [0., 0., 0., 0., 0., 0., 0.]

